import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors
import re
from cycler import cycler
from mpl_toolkits.mplot3d import Axes3D

def parse_gsrt_data(filepath):
    """
    Parses a Van Hove Gs(r,t) data file generated by the Fortran code.
    The file is expected to have data blocks for each time step.

    Args:
        filepath (str): Path to the input data file.

    Returns:
        tuple: A tuple containing:
            - dict: A dictionary with time (t) as keys and NumPy arrays
                    {'r', 'gs_mean', 'gs_std'} as values.
    """
    data = {}
    current_time = None

    print(f"Parsing file: '{filepath}'...")
    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            for line in lines:
                line = line.strip()
                if line.startswith('# t_delta ='):
                    match = re.search(r'# t_delta = \s*([\d.]+)', line)
                    if match:
                        current_time = float(match.group(1))
                        data[current_time] = []
                elif line.startswith('# r (Angstrom)') or not line:
                    continue
                elif current_time is not None:
                    parts = line.split()
                    if len(parts) == 3:
                        data[current_time].append([float(p) for p in parts])

    except FileNotFoundError:
        print(f"Error: File not found at '{filepath}'.")
        return None
    except Exception as e:
        print(f"An error occurred while parsing the file: {e}")
        return None

    # Convert lists to NumPy arrays
    for t, values in data.items():
        if not values: continue
        arr = np.array(values)
        data[t] = {
            'r': arr[:, 0],
            'gs_mean': arr[:, 1],
            'gs_std': arr[:, 2]
        }
    
    sorted_times = sorted(data.keys())
    sorted_data = {t: data[t] for t in sorted_times}

    print("File parsing complete.")
    return sorted_data

def calculate_msd(data):
    """
    Calculates the Mean Squared Displacement (MSD) from Gs(r,t) data.
    MSD(t) = 4 * pi * integral(r^4 * Gs(r,t) dr) from 0 to infinity.
    """
    times = sorted(data.keys())
    msd_values = []
    for t in times:
        r = data[t]['r']
        gs_mean = data[t]['gs_mean']
        integrand = 4 * np.pi * r**4 * gs_mean
        msd = np.trapz(integrand, r)
        msd_values.append(msd)
    return np.array(times), np.array(msd_values)

def plot_comprehensive_analysis(data, species_name, figname="gsrt_analysis_dashboard.png"):
    """
    Generates a 2x2 dashboard of plots for a comprehensive analysis.
    """
    if not data:
        print("No data available for comprehensive analysis.")
        return

    fig, axes = plt.subplots(2, 2, figsize=(18, 14))
    fig.suptitle(f'Comprehensive Dynamical Analysis for {species_name}', fontsize=20)
    
    all_times = list(data.keys())
    num_slices = 5
    indices = np.linspace(0, len(all_times) - 1, num_slices, dtype=int)
    selected_times = [all_times[i] for i in indices]

    # Panel 1: Gs(r,t) vs. r (Line Plot)
    ax1 = axes[0, 0]
    num_lines = len(selected_times)
    ax1.set_prop_cycle(cycler('color', plt.cm.viridis(np.linspace(0, 1, num_lines))))
    for t in selected_times:
        r, gs_mean = data[t]['r'], data[t]['gs_mean']
        ax1.plot(r, gs_mean, label=f't = {t:.2f} ps')
    ax1.set_xlabel('r (Å)', fontsize=12)
    ax1.set_ylabel(r'$G_s(r, t) \quad (\AA^{-3})$', fontsize=12)
    ax1.set_title('$G_s(r,t)$ at Selected Times', fontsize=14)
    ax1.legend(title="Time Delay")
    ax1.set_xlim(0, max(r))
    ax1.set_ylim(bottom=0)
    ax1.grid(True, linestyle='--')

    # Panel 2: Gs(r,t) Heatmap
    ax2 = axes[0, 1]
    times_arr = np.array(sorted(data.keys()))
    r_values = data[times_arr[0]]['r']
    gs_grid = np.array([data[t]['gs_mean'] for t in times_arr]).T
    epsilon = 1e-10
    im = ax2.pcolormesh(times_arr, r_values, gs_grid + epsilon, shading='gouraud', cmap='viridis',
                        norm=matplotlib.colors.LogNorm(vmin=np.min(gs_grid[gs_grid > 0]), vmax=np.max(gs_grid)))
    fig.colorbar(im, ax=ax2).set_label(r'$G_s(r, t) \quad (\AA^{-3})$')
    ax2.set_xlabel('Time (ps)', fontsize=12)
    ax2.set_ylabel('r (Å)', fontsize=12)
    ax2.set_title('Heatmap of $G_s(r,t)$', fontsize=14)

    # Panel 3: Decay of Gs(r=0, t)
    ax3 = axes[1, 0]
    peak_heights = [data[t]['gs_mean'][0] for t in times_arr]
    ax3.plot(times_arr, peak_heights, 'o-', color='crimson')
    ax3.set_xlabel('Time (ps)', fontsize=12)
    ax3.set_ylabel(r'$G_s(r=0, t) \quad (\AA^{-3})$', fontsize=12)
    ax3.set_title('Decay of Probability at Origin', fontsize=14)
    ax3.set_xscale('log')
    ax3.set_yscale('log')
    ax3.grid(True, which='both', linestyle='--')

    # Panel 4: Mean Squared Displacement (MSD)
    ax4 = axes[1, 1]
    msd_times, msd_values = calculate_msd(data)
    ax4.plot(msd_times, msd_values, 'o-', color='darkorange')
    # Add reference lines for ballistic (t^2) and diffusive (t^1) regimes
    if len(msd_times) > 1:
        c_ballistic = msd_values[1] / (msd_times[1]**2)
        ax4.plot(msd_times, c_ballistic * msd_times**2, 'k--', label=r'Slope 2 (Ballistic)')
        c_diffusive = msd_values[-1] / msd_times[-1]
        ax4.plot(msd_times, c_diffusive * msd_times, 'k:', label=r'Slope 1 (Diffusive)')
    ax4.set_xlabel('Time (ps)', fontsize=12)
    ax4.set_ylabel(r'MSD $(\AA^2)$', fontsize=12)
    ax4.set_title('Mean Squared Displacement from $G_s(r,t)$', fontsize=14)
    ax4.set_xscale('log')
    ax4.set_yscale('log')
    ax4.grid(True, which='both', linestyle='--')
    ax4.legend()

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(figname, dpi=300)
    print(f"Comprehensive analysis plot saved successfully: '{figname}'")
    plt.show()

def plot_3d_surface(data, species_name, figname="gsrt_3d_surface.png"):
    """
    Plots Gs(r,t) as a 3D surface plot.
    """
    if not data:
        print("No data available to plot 3D surface.")
        return

    fig = plt.figure(figsize=(14, 10))
    ax = fig.add_subplot(111, projection='3d')

    times = np.array(sorted(data.keys()))
    r_values = data[times[0]]['r']
    gs_grid = np.array([data[t]['gs_mean'] for t in times]).T

    T, R = np.meshgrid(times, r_values)
    
    # Plot the surface
    ax.plot_surface(T, R, gs_grid, cmap='viridis', edgecolor='none', norm=matplotlib.colors.LogNorm())

    ax.set_xlabel('Time (ps)', fontsize=12, labelpad=10)
    ax.set_ylabel('r (Å)', fontsize=12, labelpad=10)
    ax.set_zlabel(r'$G_s(r, t) \quad (\AA^{-3})$', fontsize=12, labelpad=10)
    ax.set_title(f'3D Surface of $G_s(r, t)$ for {species_name}', fontsize=16)

    plt.tight_layout()
    plt.savefig(figname, dpi=300)
    print(f"3D surface plot saved successfully: '{figname}'")
    plt.show()

if __name__ == '__main__':
    # --- User Settings ---
    SPECIES = 'Na'
    INPUT_FILE = f'../result/gsrt_ensemble_average_{SPECIES}.dat'
    CREATE_3D_PLOT = True # Set to False to skip the 3D plot

    # --- Run Script ---
    gsrt_data = parse_gsrt_data(INPUT_FILE)
    
    if gsrt_data:
        # Generate the comprehensive 2x2 dashboard
        plot_comprehensive_analysis(gsrt_data, SPECIES)
        
        # Optionally generate the 3D surface plot
        if CREATE_3D_PLOT:
            plot_3d_surface(gsrt_data, SPECIES)
